# Generated by Django 6.0.1 on 2026-02-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iteams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteamName', models.CharField(max_length=100)),
                ('iteamPrice', models.IntegerField()),
                ('iteamDescription', models.TextField()),
                ('iteamStock', models.PositiveIntegerField()),
                ('iteamColor', models.CharField(max_length=20, null=True)),
                ('iteamStatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'iteams',
            },
        ),
    ]
