# Generated by Django 6.0.1 on 2026-02-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_product_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentactivate',
            field=models.BooleanField(default=True),
        ),
    ]
